apiVersion: v1
kind: ConfigMap
metadata:
  name: skyline-app-config
data:
  application.yml: |-
    spring:
      datasource:
        url: jdbc:mysql://lyjking-db.c5d2wfqufspp.ap-northeast-2.rds.amazonaws.com:3306/lyjkingdb?serverTimezone=UTC
        username: admin
      jpa:
        hibernate:
          ddl-auto: validate
      mvc:
        pathmatch:
          matching-strategy: ant_path_matcher
    logging:
      level:
        root: INFO
        com.example.skyline: INFO
